version: '3'

services:
        joomladb:
                image: mysql:5.7
                volumes:
                        - joomladb_storage:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: paradox
                        MYSQL_PASSWORD: paradox
                        MYSQL_DATABASE: mydb


        joomla:
                image: joomla:latest
                restart: always
                depends_on:
                        - joomladb
                ports:
                    - 8080:80
                environment:
                        JOOMLA_DB_HOST: joomladb
                        JOOMLA_DB_USER: paradox
                        JOOMLA_DB_PASSWORD: paradox
                        JOOMLA_DB_NAME: mydb
                volumes:
                        - joomla_storage:/var/www/html
volumes:
        joomla_storage:
        joomladb_storage:        


